title: Blog
description: Grown from the seeds of just-the-docs
theme: just-the-docs

#Links
url: https://sigsando.github.io/
aux_links:
  Linkedin: https://www.linkedin.com/in/alex-barkman-b7b26a186/
  Github: https://github.com/sigSando

#Color scheme and logo
color_scheme: dark
#logo: "/assets/logo.png"

favicon_ico: "/assets/favicon.ico"
